name: Get PR Number

description: Get the PR number associated with the commit SHA.

runs:
  using: "composite"

steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Get PR number
    id: pr
    run: |
      echo "Commit SHA: ${{ github.sha }}"
      PR_NUMBER=$(curl -s -X GET \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
        | jq -r '.[0].number')
      echo "::set-output name=pr_number::${PR_NUMBER}"
