FROM ubuntu:24.04

# Install necessary packages
RUN apt-get update && \
    apt-get install -y git build-essential && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the shell script into the container
COPY build_kruize.sh /app/build_kruize.sh

# Give execute permissions to the script
RUN chmod +x /app/build_kruize.sh

# Run the script
CMD ["/app/build_kruize.sh"]

