name: 'Autotune Test Setup'
description: 'Setup minikube and clone the git repos required'
inputs:
  branch:
    description: “Kruize autotune tests branch”
    required: true

runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout autotune
      uses: actions/checkout@v2
      with:
        repository: kruize/autotune
        ref: ${{inputs.branch}}
        path: autotune

    - name: Checkout benchmarks
      uses: actions/checkout@v2
      with:
        repository: kruize/benchmarks
        path: benchmarks

    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.3.0
      with:
        minikube version: 'v1.16.0'
        kubernetes version: 'v1.19.2'
        
    - name: Start minikube
      run: kubectl get pods -n kube-system 
      shell: bash
