name: 'Upload Test results'
description: 'Archive and upload test results'
inputs:
  archive:
    description: “Archive file name”
    required: true
runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Archive results 
      if: always()
      run: tar cvf ${{inputs.archive}} autotune_test_results
      shell: bash
    - name: Upload results   
      if: always() 
      uses: actions/upload-artifact@v2
      with:
        name: autotune-results
        path: ${{inputs.archive}}
        retention-days: 2
