name: Get PR Number

on:
  push:
    branches:
      - main

jobs:
  get_pr_number:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.pr.outputs.pr_number }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR number
        id: pr
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          PR_NUMBER=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
            | jq -r '.[0].number')
          echo "::set-output name=pr_number::${PR_NUMBER}"
