name: Create PR & auto merge
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Make changes to pull request here
      - name: Send pull-request
        run: |
        
          echo "IMAGE TAG = $IMAGE_TAG  IMAGE_NAME = $IMAGE_NAME"
          IMAGE_NAME="quay.io/chandra25ms/autotune"
          IMAGE_TAG="190a6cc"
         
          REPOSITORY="chandrams/kruize"
          FOLDER="bin/$REPOSITORY"
          BRANCH_NAME="test-update"

          # Clone the remote repository and change working directory to the
          # folder it was cloned to.
          git clone \
            --depth=1 \
            --branch=main \
            https://chandrams:${{ secrets.MYTOKEN }}@github.com/$REPOSITORY \
            $FOLDER

          cd $FOLDER

          # Setup the committers identity.
          git config user.email "csubrama@redhat.com"
          git config user.name "Chandrakala Subramanyam"

          # Create a new feature branch for the changes.
          git checkout -b $BRANCH_NAME

          # Update the script files to the latest version.
          
          date > date.txt
          
          # Commit the changes and push the feature branch to origin
          git add .
          git commit -m "chore: update date"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MYTOKEN }}
          commit-message: Update date
          delete-branch: true
          title: 'Test date update'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

    
