name: Create PR and comment

on:
 worflow_dispatch

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated Pull Request"
          labels: "automated"
          body: "This is an automated pull request."

      - name: Get Pull Request Number
        id: pr_number
        run: echo "::set-output name=pr_number::$(curl -s -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" https://api.github.com/repos/${{ github.repository }}/pulls | jq '.[0].number')"

      - name: Display Pull Request Number
        run: echo "Pull Request Number: ${{ steps.pr_number.outputs.pr_number }}"
