name: Create PR and comment

on:
 workflow_dispatch

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update Hello
        run: |
          git checkout -b update_hello
          sed -i 's/chandra/Chandu/g' Hello.java > Hello.java
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated Pull Request"
          labels: "automated"
          body: "This is an automated pull request."
          branch: update_hello
          base: main

      - name: Get Pull Request Number
        id: pr_number
        run: echo "PR_NUMBER=$(curl -s -H \"Authorization:\ Bearer ${{ secrets.GITHUB_TOKEN }}\" https://api.github.com/repos/${{ github.repository }}/pulls | jq '.[0].number')" >> "$GITHUB_ENV"

      - name: Display Pull Request Number
        run: |
          echo "Pull Request Number:${{ env.PR_NUMBER }}"
          echo "Pull Request Number:${{ env.PULL_REQUEST_NUMBER }}"


      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            /retest
          pr_number: ${{ env.PULL_REQUEST_NUMBER }}
