name: Fetch PR Number


on: [push, pull_request]

jobs:
  get-pr-number:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get PR number
      id: action
      uses: kamatama41/get-pr-number-action@v0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Show the number
      run: echo "PR number is ${{ steps.action.outputs.number }}"
     
