name: Fetch PR Number

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  
  job1:
    uses: ./.github/workflows/get-pr-number.yaml  
    
  job2:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Run step using PR number
        run: |
          echo "PR number: ${{ needs.job1.env.pr_number }}"
     
