name: Fetch PR Number

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch the PR number
        uses: ./.github/workflows/get-pr-number.yml

      - name: Run step using PR number
        run: |
          echo "PR number: ${{ needs.get-pr-number.outputs.pr_number }}"
     
