name: Thanos setup on kind

on:
 workflow_dispatch:

env:
  kind-image: 'quay.io/thanos/thanos-operator:main-2024-12-24-5e131ef'
  kind-version: 'v0.24.0'

jobs:
   thanos_test:
 
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      - name: Start kind cluster
        uses: helm/kind-action@v1.11.0
        with:
          version: ${{ env.kind-version }}
          node_image: ${{ env.kind-image }}
          wait: 10s
          cluster_name: kind

      - name: Wait for cluster to bootstrap
        run: |
          kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

          LATEST=$(curl -s https://api.github.com/repos/prometheus-operator/prometheus-operator/releases/latest | jq -cr .tag_name)
          curl -sL https://github.com/prometheus-operator/prometheus-operator/releases/download/${LATEST}/bundle.yaml | kubectl create -f -

          git clone https://github.com/thanos-community/thanos-operator.git
          cd thanos-operator
          echo "******** Make install..."
          make install
          sleep 10
          echo "******** Get CRDS installed ..."
          kubectl get crds -n thanos-operator
          echo "******** Make deploy..."
          make deploy IMG="quay.io/thanos/thanos-operator:main-2024-12-24-5e131ef"
          sleep 10
          echo "******** Get pods installed ..."
          kubectl get pods -n thanos-operator-system
          echo "******** Make install-example..."
          make install-example
          echo "******** Get pods installed ..."
          kubectl get pods -n thanos-operator-system
   
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: kruize/autotune
          ref: mvp_demo
          path: autotune
