name: 'Super linter'
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout autotune
        uses: actions/checkout@v2
        with:
          repository: kruize/autotune
          

      - name: Lint Code Base
        uses: super-linter/super-linter@v6.8.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
                 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
