name: Minikube-Setup

on:
  workflow_dispatch:
 
jobs:
  minikube-setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout autotune
        uses: actions/checkout@v2
        with:
          repository: bharathappali/autotune
          ref: add-fix-for-kustomize
          path: autotune

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.6.0
        with:
          minikube version: 'v1.25.1'
          kubernetes version: 'v1.24.0'
                    
      - name: Minikube info
        run: |
          kubectl get nodes
          minikube ip      
          
      - name: Install Prometheus on minikube
        run: |
          echo Install Prometheus on minikube  
          cd autotune/scripts
          cat prometheus_on_minikube.sh 
          ./prometheus_on_minikube.sh -as -r v0.9.0   
