name: Build image with PR Number 

# Controls when the action will run. 
on:
  
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_crc:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   
      - name: Build crc
        run: |
       
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "PR_NUMBER = $PR_NUMBER"
       
      - name: Get PR number
        id: pr
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          PR_NUMBER=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
            | jq -r '.[0].number')
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
      
      - name: Print PR number
        run: echo "PR number:${{ env.PR_NUMBER }}"
