name: Build image with PR Number 

# Controls when the action will run. 
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'design/**'
      - 'examples/**'
      - 'extensions/**'
  
  
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_crc:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   
      - name: Build crc
        run: |
       
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "PR_NUMBER = $PR_NUMBER"
       
    
     
