name: Kruize Remote monitoring release tests

on:
  workflow_dispatch:
    inputs:
      tag: 
        description: 'Kruize docker image tag'
        required: true
        
jobs:
  releasetest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
      - uses: actions/checkout@v3
        with:
          repository: kruize/autotune
          path: autotune
          ref: mvp_demo
   
      - name: Run Kruize remote monitoring functional tests on minikube
        run: |
          ps -ef | grep python
          echo Running Kruize remote monitoring functional testsuite on minikube
          cd autotune
          cd tests         
          ./test_autotune.sh -c minikube -i kruize/autotune_operator:${{ github.event.inputs.image }} --testsuite=remote_monitoring_tests --testcase=negative --resultsdir=${GITHUB_WORKSPACE}
          
      - uses: actions/checkout@v3
        if: always()
        with:
          repository: chandrams/autotune
          path: autotune-fault
          ref: db_restore_on_pod_delete
          
      - name: Run Kruize remote monitoring fault tolerant tests on minikube
        if: always()
        run: |
          ps -ef | grep python
          echo Running Kruize remote monitoring fault tolerant testsuite on minikube
          cd autotune-fault
          cd tests/scripts/remote_monitoring_tests/fault_tolerant_tests         
          ./remote_monitoring_fault_tolerant_tests.sh -c minikube -i kruize/autotune_operator:0.0.14_mvp  -r  ${GITHUB_WORKSPACE}
          
      - name: Archive results
        if: always()
        run: |
          cd ${GITHUB_WORKSPACE}
          ls
          tar cvf kruize_test_results.tar kruize_test_results
          ls
          
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
           name: kruize_test_results
           path: ./kruize_test_results.tar
           retention-days: 2
