name: Run tests on comment

on:
  issue_comment:
    types: [created]
    issue_type: [pull_request]
    branch: [main, demo, test_branch]
  pull_request_review:
    types: [submitted]

jobs:
  functest:
    env:
      PR_NUMBER: ${{ github.event.issue.pull_request.number }}

    # Only run this if the user asked us to
    if: contains(github.event.comment.body, 'run functional tests')
    outputs:
      workflow_url: ${{ steps.workflow_run_info.outputs.url }}
      workflow_id: ${{ steps.workflow_run_info.outputs.id }}
    runs-on: ubuntu-20.04
    steps:
      - name: Get workflow run info
        run: |
          echo ::set-output name=url::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          echo ::set-output name=id::$GITHUB_RUN_ID
        id: workflow_run_info
        
      - name: Debug Comment Content
        run: echo "Comment :${{ github.event.comment.body }}"

      - name: Check out code
        uses: actions/checkout@v3
           
      - name: Run hello
        run: |
          echo "PR_NUMBER = ${{ env.PR_NUMBER }}"
          echo "PR_NUMBER =  ${{ github.event.number }}"
          git fetch origin pull/${{ env.PR_NUMBER }}/head:pr_${{ env.PR_NUMBER }}
          git checkout pr_${{ env.PR_NUMBER }}
          cat Hello.java
          javac Hello.java
          java Hello
          
  reportFailure:
    runs-on: ubuntu-latest
    needs: [functest]
    if: failure()
    steps:
    - name: Create comment
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          comment_body = `
          @${{ github.actor }} Build(s) failed.
          Workflow Run ID: [${{ needs.functest.outputs.workflow_id }}](${{ needs.functest.outputs.workflow_url }})
          `;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment_body
          })

  reportCancelled:
    runs-on: ubuntu-latest
    needs: [functest]
    if: cancelled()
    steps:
    - name: Create comment
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          comment_body = `
          @${{ github.actor }} Build(s) cancelled.
          Workflow Run ID: [${{ needs.functest.outputs.workflow_id }}](${{ needs.functest.outputs.workflow_url }})
          `;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment_body
          })
          
  reportSuccess:
    runs-on: ubuntu-latest
    needs: [functest]
    if: success()
    steps:
    - name: Create comment
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          comment_body = `
          @${{ github.actor }} Build(s) successful.
          Workflow Run ID: [${{ needs.functest.outputs.workflow_id }}](${{ needs.functest.outputs.workflow_url }})
          `;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment_body
          })
