name: Run tests on comment

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  functest:

    # Only run this if the user asked us to
    if: github.event.comment.body == 'run functional tests'

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
      - uses: actions/checkout@v3
        with:
          repository: kruize/autotune
          path: autotune
          ref: mvp_demo
      - name: Build crc
        run: |
          echo Build crc
          ./build.sh -i autotune_operator:test
          docker images | grep autotune
    
      - name: Run Kruize remote monitoring tests on minikube
        run: |
          ps -ef | grep python
          echo Running Kruize remote monitoring testsuite on minikube
          cd autotune
          cp ./manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml ./manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml.old
          sed -e "s/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g" ./manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml.old > ./manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml
          cat ./manifests/crc/default-db-included-installation/minikube/kruize-crc-minikube.yaml

          cd tests         
          ./test_autotune.sh -c minikube -i autotune_operator:test --testsuite=remote_monitoring_tests --resultsdir=${GITHUB_WORKSPACE}
          
      - name: Archive results
        if: always()
        run: |
          cd ${GITHUB_WORKSPACE}
          ls
          tar cvf kruize_test_results.tar kruize_test_results
          ls
          
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
           name: kruize_test_results
           path: ./kruize_test_results.tar
           retention-days: 2
