name: Run tests on comment

on:
  issue_comment:
    types: [created]
    issue_type: [pull_request]
    branch: main
  pull_request_review:
    types: [submitted]
env:
  ACTIONS_STEP_DEBUG: true
  
jobs:
  functest:

    # Only run this if the user asked us to
    if: contains(github.event.comment.body, 'run functional tests')

    runs-on: ubuntu-20.04
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        
      - name: Debug Comment Content
        run: echo "Comment :${{ github.event.comment.body }}"

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Run hello
        run: |
          javac Hello.java
          java Hello
    
   
