name: Run tests on comment

on:
  issue_comment:
    types: [created]
    issue_type: [pull_request]
    branch: [main, demo, test_branch]
  pull_request_review:
    types: [submitted]

jobs:
  functest:
  
    # Only run this if the user asked us to
    if: contains(github.event.comment.body, 'run functional tests')
    outputs:
      workflow_url: ${{ steps.workflow_run_info.outputs.url }}
      workflow_id: ${{ steps.workflow_run_info.outputs.id }}
    runs-on: ubuntu-20.04
  
    steps:
      - name: Get workflow run info
        run: |
          echo "url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
          echo "id::$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
         
        id: workflow_run_info
        
      - name: Debug Comment Content
        run: echo "Comment :${{ github.event.comment.body }}"

     
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
              
      - name: Run hello
        run: |
         
          cat Hello.java
          javac Hello.java
          java Hello
          
  reportFailure:
    runs-on: ubuntu-latest
    needs: [functest]
    if: failure()
    steps:
    - name: Create comment
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          comment_body = `
          @${{ github.actor }} Build(s) failed.
          Workflow Run ID: [${{ needs.functest.outputs.workflow_id }}](${{ needs.functest.outputs.workflow_url }})
          `;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment_body
          })

  reportCancelled:
    runs-on: ubuntu-latest
    needs: [functest]
    if: cancelled()
    steps:
    - name: Create comment
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          comment_body = `
          @${{ github.actor }} Build(s) cancelled.
          Workflow Run ID: [${{ needs.functest.outputs.workflow_id }}](${{ needs.functest.outputs.workflow_url }})
          `;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment_body
          })
          
  reportSuccess:
    runs-on: ubuntu-latest
    needs: [functest]
    if: success()
    steps:
    - name: Create comment
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          comment_body = `
          @${{ github.actor }} Build(s) successful.
          Workflow Run ID: [${{ needs.functest.outputs.workflow_id }}](${{ needs.functest.outputs.workflow_url }})
          `;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment_body
          })
