name: Bump version
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout autotune
        uses: actions/checkout@v2
        with:
          repository: kruize/autotune
          path: autotune

      - name: Checkout benchmarks
        uses: actions/checkout@v2
        with:
          repository: kruize/benchmarks
          path: benchmarks

      - name: Build autotune
        run: |
          echo Build autotune
          cd autotune
          ./build.sh -i autotune:0.0.10_mvp 
          docker images | grep autotune    
  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout autotune
        uses: actions/checkout@v2
        with:
          repository: kruize/autotune
          path: autotune
      - name: Run the test
        run: |
          cd autotune/tests
          ./test_autotune.sh -c minikube -r ${GITHUB_WORKSPACE}/benchmarks --resultsdir=${GITHUB_WORKSPACE}/kruize_test_result -i --testsuite=remote_monitoring_test --testcase=test_update_results
    
  push-to-dockerhub:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Push
        run: |
          docker tag autotune:0.0.10_mvp chandra25ms/autotune:0.0.10_mvp
          docker push chandra25ms/autotune:0.0.10_mvp
          
  tag-version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: 0.0.10_mvp
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          
      
