name: Release Kruize
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout autotune
        uses: actions/checkout@v2
        with:
          repository: kruize/autotune
          ref: mvp_demo
          path: autotune
      - name: Build autotune
        run: |
          echo Build autotune
          cd autotune
          ./build.sh -i autotune:0.0.10_mvp 
          docker images | grep autotune    
  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout autotune
        uses: actions/checkout@v2
        with:
          repository: kruize/autotune
          ref: mvp_demo
          path: autotune      
      - name: Checkout benchmarks
        uses: actions/checkout@v2
        with:
          repository: kruize/benchmarks
          path: benchmarks
      - name: Run the test
        run: |
          cd autotune/tests
          ./test_autotune.sh -c minikube -r ${GITHUB_WORKSPACE}/benchmarks --resultsdir=${GITHUB_WORKSPACE}/kruize_test_results -i autotune:0.0.10_mvp --testsuite=remote_monitoring_tests --testcase=test_update_results
      - name: Archive results
        if: always()
        run: |
          cd ${GITHUB_WORKSPACE}
          tar zcvf kruize_test_results.tgz kruize_test_results
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: kruize-results
          path: ./kruize_test_results.tgz
          retention-days: 2  
    
  push-to-dockerhub:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Push
        run: |
          docker tag autotune:0.0.10_mvp chandra25ms/autotune:0.0.10_mvp
          docker push chandra25ms/autotune:0.0.10_mvp
        
  push-to-quay:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: quay.io

      - name: Docker Push
        run: |
          docker tag autotune:0.0.10_mvp quay.io/chandra25ms/autotune:0.0.10_mvp
          docker push quay.io/chandra25ms/autotune:0.0.10_mvp
          
  tag-version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: 0.0.10_mvp
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          
      
