name: Quay

# Controls when the action will run. 
on:

  # Triggers the workflow on push event but only for the mvp_demo branch
  push:
    branches: [ mvp_demo ]
    paths-ignore:
      - 'docs/**'
      - 'design/**'
      - 'examples/**'
      - 'extensions/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # This workflow contains three jobs called "build job" , "deploy autotune" and "deploy crc"
  build_job:
 
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: kruize/autotune
          ref: mvp_demo
          path: autotune
      
        
      - name: Build monitoring
        run: |
          echo Build monitoring
          cd autotune
          ./build.sh -i autotune_operator:test_quay -o autotune_optuna:test_quay
          docker images | grep autotune
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: |
          docker tag autotune_operator:test_quay quay.io/kruize/autotune_operator:test_quay
          docker push quay.io/kruize/autotune_operator:test_quay
