name: Raise a PR and Label it

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Update the file
        run: |
          
          sed -i "s/chandra/Chandrakala/g" ./Hello.java
          cat ./Hello.java
                   
          git config --global user.email "chandrams@gmail.com"
          git config --global user.name "chandrams"
          git add Hello.java
          git commit -m "Updated Hello.java"
     
      - name: Create pull request
        if: steps.compare_files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Updated Hello.java'
        
      - name: Display Pull Request Number
        run: |
          echo "Pull Request Number:${{ env.PULL_REQUEST_NUMBER }}"

      - name: Comment on PR
        run: |
          gh pr edit  ${{ env.PULL_REQUEST_NUMBER }} --add-labels "auto-merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
