name: Test-workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Github Repository'
        required: false
        default: 'chandrams/autotune'
      branch:
        description: 'Branch name'
        required: false
        default: 'hpo'
      image: 
        description: 'Autotune Docker image'
        required: false
        default: 'kruize/autotune_operator:test'
      testsuite:
         description: 'Testsuite to be executed'
         required: false
         default: 'hpo_api_tests'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Repo: ${{ github.event.inputs.repository }}"
          echo "Branch: ${{ github.event.inputs.branch }}"
          echo "image: ${{ github.event.inputs.image }}"
          echo "Testsuite: ${{ github.event.inputs.testsuite }}"
   
      - name: Checkout autotune
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.branch }}
          path: autotune

      - name: Checkout benchmarks
        uses: actions/checkout@v2
        with:
          repository: kruize/benchmarks
          path: benchmarks

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
      - name: Start minikube
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
     
          
      - name: Run Analyzer API tests
        run: |
          echo Running API tests
          cd autotune/tests
          ./test_autotune.sh -c minikube -i kruize/${{ github.event.inputs.image }} --tctype=functional --testsuite=${{ github.event.inputs.testsuite }} --resultsdir=${GITHUB_WORKSPACE} -r ${GITHUB_WORKSPACE}/benchmarks
      - name: Archive results
        if: always()
        run: |
          cd ${GITHUB_WORKSPACE}
          ls
          tar cvf autotune_test_results.tar autotune_test_results
          ls
          
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
           name: autotune-results
           path: ./autotune_test_results.tar
           retention-days: 2
