name: Test Composite Action
# Controls when the action will run. 
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'design/**'
      - 'examples/**'
      - 'extensions/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  listapp_test:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Autotune Test setup
        uses: ./.github/actions/test-setup
    
      - name: Run Analyzer API tests
        run: |
          echo Running Basic API tests
          ls
          cd autotune/tests
          ./test_autotune.sh -c minikube -i kruize/autotune:int-test --tctype=functional --testsuite=basic_api_tests --testcase=listapplications --resultsdir=${GITHUB_WORKSPACE} -r ${GITHUB_WORKSPACE}/benchmarks    
      - name: Upload Test results
        uses: ./.github/actions/upload-results
        with:
         archive: "apps.tar"
          
  listapplayers_test:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Autotune Test setup
        uses: ./.github/actions/test-setup
    
      - name: Run Analyzer API tests
        run: |
          echo Running Basic API tests
          ls
          cd autotune/tests
          ./test_autotune.sh -c minikube -i kruize/autotune:int-test --tctype=functional --testsuite=basic_api_tests --testcase=listapplayer --resultsdir=${GITHUB_WORKSPACE} -r ${GITHUB_WORKSPACE}/benchmarks    
          
      - name: Upload Test results
        uses: ./.github/actions/upload-results   
        with:
         archive: "applayers.tar"
          
          
